### ISSUE TITLE
How to add argument -shell-escape  for compile

### ISSUE THREAD

**Issue by sunyongke** [kpym/latex-fast-compile#1]
When I compile my tex file, it hits me to add  argument -shell-escape.

`./latex-fast-compile -x  ctexnetbook.tex --no-watch --compiles-at-start=2 
Adapt preamble to xelatex.
Switch to OT1 encoding in the preamble. And restore TU encoding later.
 create ctexnetbook.preamble.tex
 create ctexnetbook.body.tex
::::::: Precompile...done [4.2s]
----------------------------------------------------------------------------- sanitized log
! Package minted Error: You must invoke LaTeX with the -shell-escape flag.

See the minted package documentation for explanation.
l.161 \usemintedstyle
                     {bw} 
Here is how much of TeX's memory you used:
----------------------------------------------------------------------------- end log
The compilation finished with errors.
Error: Problem with the header compilation.
exit status 1
 remove ctexnetbook.preamble.tex
 remove ctexnetbook.body.tex`

**Comment by kpym** [comment]
This was not possible before, but I have [added](https://github.com/kpym/latex-fast-compile/releases/tag/v0.8.0) a new flag `option` which allows you to specify additional options for the compiler.
So now you can specify `-shell-escape` like this
```bash
./latex-fast-compile -x ctexnetbook.tex --no-watch --compiles-at-start=2 --option=-shell-escape
```

**Comment by sunyongke** [comment]
Thank you for your update. It is working now, and the new version is perfect!
